USE Cloud_Project;

CREATE TABLE users(
	UserID INT(11) AUTO_INCREMENT NOT NULL,
	Username VARCHAR(50) NOT NULL UNIQUE,
	email VARCHAR(50) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL,
);

CREATE TABLE files(
	FileID INT(11) AUTO_INCREMENT NOT NULL,
	FileName VARCHAR(30) NOT NULL,
	Extension VARCHAR(6) NOT NULL,
	MIME VARCHAR(30),
	Possessore INT(11) NOT NULL,
	PRIMARY KEY (fileID),
	FOREIGN KEY (Possessore) REFERENCES Users(UserID)
);

