name: Auto-Upload
on:
  push:
    branches: [ main ]
  workflow_dispatch:
 
jobs:

  deploy-via-sftp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.1
        with:
          username: jecker247
          server: 82.61.87.38
          port: 22
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
 
          
          # will put all file under this path
          local_path: ./* # default is ./*
          # files will copy to under remote_path
          remote_path: /var/www
          
          # sftp args
          args: '-o ConnectTimeout=5'
